name: Cypress Auto-Present E-Office

on:
  workflow_dispatch:
    inputs:
      npp:
        description: 'Your NPP to login eoffice'
        required: true
        type: string
      password:
        description: 'Password to login eoffice'
        required: true
        type: string
      clock_out:
        description: 'Time when you clock out 17:00 format'
        required: true
        default: 'DEFAULT'
        type: string
      clock_in:
        description: 'Time when you clock in 7:00 format'
        required: true
        type: string
      date_diff:
        description: '-1 for yesterday 0 for today'
        required: true
        default: '0'
        type: string
      reason:
        description: 'Reason of creating hadir'
        required: true
        default: 'E-Absensi tidak dapat digunakan'
        type: string
      witness:
        description: 'Your SPV, NPP - NAME, look in e-office'
        required: true
        type: string
      reviewer1:
        description: 'Reviewer 1'
        required: true
        type: string
      reviewer2:
        description: 'Reviewer 2'
        required: true
        type: string
      comment:
        description: 'Your comment when submit kehadiran'
        required: true
        default: 'Mohon approvalnya mas, terima kasih'
        type: string

jobs:
  cypress-run:
    name: Running Cypress Auto-Present Job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install ld
        run: npm install -g lambdatest-cypress-cli
      - name: Run lambdatest command
        run: lambdatest-cypress run --username=gafiliano --ak=${{ secrets.LT_ACCESS_KEY }} --envs "IS_SUBMIT=false,NPP=${{ inputs.npp }},PASSWORD=${{ inputs.password }},CLOCK_OUT=${{ inputs.clock_out }},CLOCK_IN=${{ inputs.clock_in }},DATE_DIFF=${{ inputs.date_diff }},REASON=${{ inputs.reason }},WITNESS=${{ inputs.witness }},REVIEWER1=${{ inputs.reviewer1 }},REVIEWER2=${{ inputs.reviewer2 }},COMMENT=${{ inputs.comment }}"
